sonar.projectKey=Macro-Hard-Ecom_Macro-Hard-Ecom-Order-service
sonar.organization=macro-hard-ecom


sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,.github/**